model:
  hidden_dim: 768 # hidden dim
  model_type: BERT-disk # BERT-disk, ELMo-disk, 
  use_disk: False
  model_layer: 7 # BERT-base: {1,...,12}; ELMo: {1,2,3}
probe:
  task_name: demo
  maximum_rank: 768
  psd_parameters: True
  depth_params_path: /path/to/params/example/bert-base-cased-7/params/bertbase7-depth-probe.params
  distance_params_path: /path/to/params/example/bert-base-cased-7/params/bertbase7-distance-probe.params
reporting:
  root: example/results

 